<a href="https://colab.research.google.com/github/shevochkkaaa/lab-robota/blob/main/%D0%94%D0%BE%D0%B1%D1%80%D0%BE_%D0%BF%D0%BE%D0%B6%D0%B0%D0%BB%D0%BE%D0%B2%D0%B0%D1%82%D1%8C_%D0%B2_Colaboratory!.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Лабораторна робота №4, Шевченко Валеія, завдання №2

In [2]:
import numpy as np
import numpy as np

# Define dimensions N and M
N, M = 5, 4  # Example dimensions, can be modified as needed

# Create a rectangular matrix A with random elements
A = np.random.rand(N, M)

# Calculate the mean for each row
row_means = A.mean(axis=1)

# Calculate the mean for each column
column_means = A.mean(axis=0)

print(A, row_means, column_means)

[[0.9645764  0.98568803 0.57662262 0.66633071]
 [0.87683281 0.58536909 0.78800567 0.65712038]
 [0.96280062 0.01051756 0.01526835 0.44198857]
 [0.86421615 0.58493949 0.02960689 0.42444459]
 [0.25379755 0.35665606 0.98204381 0.3286668 ]] [0.79830444 0.72683199 0.35764378 0.47580178 0.48029106] [0.78444471 0.50463405 0.47830947 0.50371021]
